# Generated by Django 5.0.3 on 2024-03-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_data_ticker'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='data',
            index=models.Index(fields=['ticker'], name='app_data_ticker_2e93a2_idx'),
        ),
        migrations.AddIndex(
            model_name='data',
            index=models.Index(fields=['date'], name='app_data_date_b96ef4_idx'),
        ),
    ]
